
import FreeCAD as App
App.Console.PrintMessage("Macro started!\n")


import os, sys

import sys
import FreeCAD

import os
import sys

# Get the exact directory where THIS macro file is currently saved
macro_path = os.path.dirname(__file__)

# Add it to the Python path if it isn't already there
if macro_path not in sys.path:
    sys.path.append(macro_path)

# Now your original import will work perfectly!
import Librs.Folders as Folders
import Librs.Folders as Folders
import Librs.Planes as Planes
import Librs.Patterns as Patterns
import Librs.Spreadsheets as SpreadSheet


print("Folders:", Folders)
print("Planes:", Planes)
print("Patterns:", Patterns)
print("SpreadSheet:", SpreadSheet)


from PySide import QtCore
import FreeCADGui as Gui
import FreeCAD as App
import importlib

importlib.reload(Folders)
importlib.reload(Planes)
importlib.reload(Patterns)
importlib.reload(SpreadSheet)


hexSeparation       = .2
hexExtrusion        = -2
hexRadius           = 2
planeOffset         = -3
userSheetLabel      = 'EditMe'
autoGeneratedLabel  = 'AutoGenerated'
objects = []

def delete_after_delay(objs, delay_ms=10000):
    """Delete the given objects after delay_ms milliseconds."""
    def _delete():
        doc = App.ActiveDocument
        for obj in objs:
            try:
                if obj and obj in doc.Objects:
                    doc.removeObject(obj.Name)
            except Exception:
                pass
        doc.recompute()
    QtCore.QTimer.singleShot(delay_ms, _delete)



def main():
    # 1. Initialize our spreadsheet management system
    sheet = SpreadSheet.SpreadSheet()
    userSpreadsheet = sheet.userSpreadSheet()

    # 2. Grab the user selection and create our 3D spatial plane reference
    plane = Planes.Plane()
    binder = plane.createShapeBinder()
    App.ActiveDocument.recompute()

    # 3. Create the 2D offset boundaries on that plane
    offset2D = plane.createOffset2D(binder)   
    App.ActiveDocument.recompute()

    # 4. Compute the auto-generated grid variables based on the 2D offset's bounding box
    autoGeneratedSpreadsheet = sheet.compute(offset2D=offset2D)

    # 5. Initialize the pattern generator, linking it to our sheets and plane orientation
    hexagons = Patterns.HexagonalPattern(
        userSheet=userSpreadsheet,
        autoGeneratedSheet=autoGeneratedSpreadsheet,
        offset2D=offset2D,
        pattern_type='hexagons'
    )

    # 6. Generate the hexagon arrays (this handles local 3D orientation internally now)
    hexagons.create()
    hexagons.align(binder)
    App.ActiveDocument.recompute()
    #fused = hexagons.extrude()

    #cutA = plane.doc.addObject('Part::Cut', 'Cut_OffsetA_minus_Hexagons')
    #cutA.Base = extrusion_a
    #cutA.Tool = fused

    #cutB = plane.doc.addObject('Part::Cut', 'Cut_OffsetB_minus_Body')
    #cutB.Base = plane.body
    #cutB.Tool = extrusion_b

    

    plane.doc.recompute()
    Gui.SendMsgToActiveView("ViewFit")


if __name__ == "__main__":
    main()
